### ISSUE TITLE
Transitions buffered

### ISSUE THREAD

**Issue by MarkHedley** [craftedpixelz/Craftyslide#3]
Hi,
Just installed this excellent implmentation of a slideshow. The only problem I have is that it appears that transitions are being buffered if the browser does not have the focus. When you next view the browser the images quickly flick to catch up ignoring the delay time, i.e. this obviously only occurs where pagination is false. I just checked and this affects Firefox and not IE!!!!

Thanks for any help
Mark

**Comment by craftedpixelz** [comment]
Strange, can't seem to replicate this. What version of Firefox was it in?

**Comment by MarkHedley** [comment]
Hi, currently using version 5. I have just checked and with the problem page on a seperate tab, switching to another tab for a while then back exhibits the same behaviour.

**Comment by craftedpixelz** [comment]
Turns out this is a bug/change made in jQuery 1.6.

I've included a fix that should circumvent the issue. You can grab the updated file from here:
http://projects.craftedpixelz.co.uk/craftyslide/js/craftyslide.min.js

**Comment by MarkHedley** [comment]
Excelent, thankyou
