### ISSUE TITLE
auto mode and pagination

### ISSUE THREAD

**Issue by ghost** [craftedpixelz/Craftyslide#4]
Hi,

It will be nice if auto mode and pagination can work together.

Best regards,
ZPop

**Comment by craftedpixelz** [comment]
I may add this in a future release, time permitting.

**Comment by danielfos** [comment]
Find this part of code:

if(options.pagination===true){paginate();}else{auto();}

change it to:

if(options.pagination===true){paginate();auto();}

And always set pagination to "true"

That way you can get pagination and automode working together! ;)

**Comment by ghost** [comment]
Thank you.
I'll try.

**Comment by danielfos** [comment]
Actualy, pagination doesn't work in automode :P

The pagination is there, but no action on those buttons, even if the slides are moving.

Sorry!
I'll try another way..

**Comment by craftedpixelz** [comment]
I disabled pagination during auto mode because I didn't have time to get the 2 working together initially. I've planned to add this feature in the next release.

Stay tuned!

**Comment by danielfos** [comment]
That will be great! :D

**Comment by f15u** [comment]
Any update?

**Comment by zacparker** [comment]
Would be excellent to see this implemented. If I find time to do this, I will submit a pull request.

**Comment by justinbeginner** [comment]
This is not working in chrome only display or rotted  two images after that it will stop !! Any Solution..

**Comment by linkzero** [comment]
Issue on Chrome... images will rotate when I set delay to 100, 200, 300, but anything above that the images will not load beyond the second one... only in Chrome... works in IE and FFX

**Comment by paulsonkf** [comment]
In chrome not showing more than 2 slide(image) . Any solution for it .

**Comment by OneHoopyFrood** [comment]
I have solved both these issues in my fork. It's not elegant yet, but it works.
